INSERT INTO Orders(delivery_status) values ('on the way')
INSERT INTO Orders(delivery_status) values ('pending')
INSERT INTO Orders(delivery_status) values ('delivered')
INSERT INTO Orders(delivery_status) values ('pending')
INSERT INTO Orders(delivery_status) values ('delivered')
INSERT INTO Orders(delivery_status) values ('pending')
INSERT INTO Orders(delivery_status) values ('delivered')
INSERT INTO Orders(delivery_status) values ('on the way')